/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_CONFDIR "/usr/local/etc/veertu"
#define CONFIG_QEMU_DATADIR "/usr/local/share/veertu"
#define CONFIG_QEMU_DOCDIR "/usr/local/share/doc/veertu"
#define CONFIG_QEMU_MODDIR "/usr/local/lib/veertu"
#define CONFIG_QEMU_LOCALSTATEDIR "/usr/local/var"
#define CONFIG_QEMU_HELPERDIR "/usr/local/libexec"
#define CONFIG_QEMU_LOCALEDIR "/usr/local/share/locale"
#define HOST_X86_64 1
#define CONFIG_POSIX 1
#define CONFIG_DARWIN 1
#define CONFIG_SLIRP 1
#define CONFIG_SMBD_COMMAND "/usr/sbin/smbd"
#define CONFIG_AUDIO_DRIVERS \
    &coreaudio_audio_driver,\

#define CONFIG_COREAUDIO 1
#define CONFIG_BDRV_RW_WHITELIST\
    NULL
#define CONFIG_BDRV_RO_WHITELIST\
    NULL
#define CONFIG_VNC 0
#define CONFIG_VNC_TLS 1
#define CONFIG_VNC_SASL 1
#define CONFIG_VNC_PNG 1
#define CONFIG_VNC_WS 1
#define CONFIG_FNMATCH 1
#define CONFIG_UUID 1
#define QEMU_VERSION "1.0"
#define QEMU_PKGVERSION ""
#define CONFIG_COCOA 1
#define CONFIG_CURL m
#define CONFIG_IOVEC 1
#define CONFIG_MADVISE 1
#define CONFIG_POSIX_MADVISE 1
#define CONFIG_USB_LIBUSB 1
#define CONFIG_BSD 1
#define CONFIG_QOM_CAST_DEBUG 1
#define CONFIG_COROUTINE_BACKEND sigaltstack
#define CONFIG_COROUTINE_POOL 1
#define CONFIG_CPUID_H 1
#define CONFIG_INT128 1
#define CONFIG_VHDX 1
#define CONFIG_TRACE_NOP 1
#define CONFIG_TRACE_FILE trace
#define HOST_DSOSUF ".so"
